---
title: Presentations
listing:
  - id: presentations
    contents: "*.qmd"
    exclude:
      file: index.qmd
    sort: date desc
    categories: true
    feed: true
    sort-ui: true
    filter-ui: true
    fields:
      - title
      - description
      - author
      - venue
      - location
      - categories
      - image
      - image-alt
      - doi
      - date
format:
  html:
    embed-resources: true
    self-contained: true
