---
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published
  workflow_dispatch: null
name: Publish
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: read
  discussions: read
  packages: write
  pages: write
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: altdoc-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: false
      - uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b
        with:
          tinytex: true
      - name: Build site
        run: |
          bash copy_dirs.sh
          uv run quarto render
          bash copy_dirs.sh
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          branch: gh-pages
          folder: _site
